"""Initial migration

Revision ID: 55d31dacccc0
Revises: 
Create Date: 2026-08-19 16:12:18.278032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55d31dacccc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('parsed_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_notes_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_notes_path'), ['path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_notes_path'))
        batch_op.drop_index(batch_op.f('ix_parsed_notes_content_hash'))

    op.drop_table('parsed_notes')
    # ### end Alembic commands ###
